package HrBCmodel.bc.staticLOV;

import model.shared.extensions.ExtViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 18 02:59:22 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RefBrandImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RefBrandImpl() {
    }
}

