package HrBCmodel.bc.staticLOV;

import model.shared.extensions.ExtViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 16 00:52:15 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RefCountriesImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RefCountriesImpl() {
    }
}

