package HrBCmodel.bc.staticLOV;

import model.shared.extensions.ExtViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 18 03:01:19 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RefCarModelImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RefCarModelImpl() {
    }
}

