package HrBCmodel.bc.staticLOV;

import model.shared.extensions.ExtViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 19 00:10:50 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RefRaisedByImpl extends ExtViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RefRaisedByImpl() {
    }
}

